services:
  app:
    container_name: montrack-app
    build:
        context: .
        dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - '8080:8080'
  postgres:
    container_name: montrack-db
    image: 'postgres:17.2'
    env_file: .env
    ports:
      - '5433:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  redis:
    container_name: montrack-redis
    image: 'redis:7.4'
    ports:
      - '6379:6379'

  prometheus:
    container_name: montrack-prometheus
    image: 'prom/prometheus:v3.4.0'
    ports:
      - '9090:9090'
    volumes:
      - ./observability/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./observability/prometheus/alerting-rules.yaml:/etc/prometheus/alerting-rules.yaml

  grafana:
    container_name: montrack-grafana
    image: 'grafana/grafana:12.0.0-ubuntu'
    ports:
      - '3001:3000'
    depends_on:
      - prometheus
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
  alertmanager:
    container_name: montrack-alertmanager
    image: 'bitnami/alertmanager:latest'
    ports:
      - '9093:9093'
  mailhog:
    container_name: montrack-mailhog
    image: mailhog/mailhog:latest
    ports:
        - 1025:1025
        - 8025:8025
volumes:
  postgres_data: