apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: montrack-api-hpa
  namespace: montrack
  labels:
    app: montrack-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: montrack-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90