apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: montrack-api-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: base-ingress
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: montrack-api-service
            port:
              number: 80