apiVersion: v1
kind: Service
metadata:
  name: montrack-api-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: montrack-api
  ports: 
    - name: http
      port: 80
      targetPort: 8080
  
