groups:
  - name: services_alert
    rules: 
      - alert: ServiceIsDown
        expr: up{instance="montrack-app:8080", job="montrack-app", service="montrack-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "The service {{ $labels.instance }} has not been reachable for more than 1 minute."
      - alert: High4xxxErrorRate
        expr: sum(rate(http_server_requests_seconds_count{status=~"4.."}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High 4xx error rate"
          description: "The service {{ $labels.instance }} has a high 4xx error rate."
      - alert: High5xxErrorRate
        expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High 5xx error rate"
          description: "The service {{ $labels.instance }} has a high 5xx error rate."
      - alert: Sudden4xxErrorRateSpike
        expr: increase(http_server_requests_seconds_count{status=~"4.."}[25m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Sudden spike in 4xx error rate"
          description: "The service {{ $labels.instance }} has a sudden spike in 4xx error rate."
      - alert: Sudden5xxErrorRateSpike
        expr: increase(http_server_requests_seconds_count{status=~"5.."}[25m]) > 10
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Sudden spike in 5xx error rate"
          description: "The service {{ $labels.instance }} has a sudden spike in 5xx error rate."

            