scrape_configs:
  - job_name: 'montrack-app'
    metrics_path: /actuator/prometheus
    scrape_interval: 2s
    static_configs:
      - targets: ['montrack-app:8080']
        labels:
          service: 'montrack-app'
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['montrack-alertmanager:9093']

rule_files: 
  - '/etc/prometheus/alerting-rules.yaml'