apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  labels:
    app: montrack-api-cicd
gke:
  cluster: projects/sepasangselamanya/locations/asia-southeast2/clusters/montrack-api-prod
